# This file is designed for use as a logging configuration for pyshell-based scripts.
# It can easily be used by setting the script's supercfg attribute properly:
#  supercfg = [('pyshell','logging.yml')]
# or
#  supercfg = PYSHELL_LOGGING
logging:
  version: 1
  formatters:
    stdout:
      format: "%(levelname)-8s --> %(message)s"
    file:
      format: "%(asctime)s : %(levelname)s : %(processName)s %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: stdout
      level: INFO
    file:
      class : logging.handlers.TimedRotatingFileHandler
      formatter: file
      when: 'H'
      interval: 2
      filename: script.log
      backupCount: 2
      encoding: utf-8
    warnings:
      class : logging.handlers.TimedRotatingFileHandler
      formatter: file
      when: 'H'
      interval: 2
      filename: script.Warnings.log
      backupCount: 2
      encoding: utf-8
      level: WARNING
  loggers:
    py.warnings:
      handlers:
        - warnings
    pyshell:
      hanlders:
        - file
      level: DEBUG
  root:
    level: DEBUG
    handlers:
      - console
      - file